### ISSUE TITLE
Importing .ts files from within .vue files throws error

### ISSUE THREAD

**Issue by ManuelSch** [xerebede/gridsome-starter-typescript#3]
Hi,

whenever I try to import something from within a .vue file, `gridsome develop` and `gridsome build` fail:

```
ERROR  Failed to compile with 1 errors                                                                                                                                       5:23:30 PM

This relative module was not found:

* ../util/validate-email in ./node_modules/ts-loader??ref--15-0!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/pages/Index.vu
e?vue&type=script&lang=ts&

```

**Test setup to recreate the error:**

Create a new project using `gridsome create gridsome-ts https://github.com/cleitonper/gridsome-starter-typescript.git` (as described in the readme).

Add a new folder "util" inside "src", then create `validate-email.ts` inside with the following content:
```
export function validateEmail(email: string): string {
    return '';
}
```

In `src/pages/Index.vue`, change the script to the following:
```
<script lang="ts">
  import { Component, Vue } from 'vue-property-decorator';
  import { validateEmail } from '../util/validate-email';

  @Component
  export default class HomePage extends Vue {
    public validate() {
        validateEmail('test@test.test');
    }
  }
</script>
```

I hope you can help resolve the issue!

**Comment by ManuelSch** [comment]
The source of this error seems to lie in https://github.com/xerebede/gridsome-plugin-typescript, see also: https://github.com/xerebede/gridsome-plugin-typescript/issues/12 and https://github.com/xerebede/gridsome-plugin-typescript/pull/11

**Comment by xerebede** [comment]
This issue was fixed at [`gridsome-plugin-typescript`](https://github.com/xerebede/gridsome-plugin-typescript) `v0.4.0` ([`#13`](https://github.com/xerebede/gridsome-plugin-typescript/pull/13)). The `starter` was updated too, to reflect the plugin changes. You can try it out now.

Thanks!
